### PR TITLE
CMake support, memory leak fixes, and random linter cleanup

### PR DESCRIPTION
**Pull request by garlic-hub**
Hello. Found this project while looking for a remote instrument panel setup. Compiled on raspi 3 because I don't have a 4. If you like what you see I'll continue to create these kinds of fixes to get into a more modern C++ state

### CODE REVIEW

**Comment by garlic-hub** [comment]
@scott-vincent Sorry, I'm not trying to be annoying or anything but I was hoping you could review my changes.

**Comment by scott-vincent** [comment]
Sorry, but I don't see your memory leak fix. Which file is it in?

**Comment by garlic-hub** [comment]
Ah that's adding the missing virtual keyword in instrument.h

**Comment by scott-vincent** [comment]
Doesn't cause a memory leak for me. All your other changes just look like noise. I don't recommend using a Pi 3. The instrument panel is receiving data from the data link and updating all the instruments at 30 fps. The Pi 4 has a different (improved) OpenGL implementation to Pi 3.

**Comment by garlic-hub** [comment]
I'll try to pick up a pi4 soon. If you're open to discussion, I do believe that the changes are more than just noise. Those libraries are marked as deprecated from a c++ standpoint, and nullptr was introduced to c++ to prevent bugs when it comes to pointers. As maintainer you have final say of course, but a these suggestions do come from linters as well and not just my own beliefs. For the memory leak, I will concede I didn't actually get a chance to run valgrind or similar. I do believe it is still good practice to mark destructors as virtual when inheritance is at play. I can edit the patch description if you like. Sorry for that.

**Comment by garlic-hub** [comment]
@scott-vincent Hey I wanted to apologize again. If I insulted you or anything like that, it was not my intention. Looking back I can see how this PR can come off as abrasive and I should have worded/tested things better. I do want to contribute to the repository and help the community enjoy more physical flight sim setups. Sorry again.

**Pull request closed without merging**
