### PR TITLE
Fix inaccurate RPM

### LINKED ISSUE #26: Inaccurate RPM
- The indicated RPM is lower than the actual RPM (by ~200 at high RPM) on the Cessna single engine piston aircraft 
- The indicated RPM is off the scale when using the Shock Ultra aircraft with its high-reving Rotax engine

### PR DESCRIPTION
**Pull request by emxsys**
This pull request improves the accuracy of the indicated RPM on the standard RPM gauge and the Savage Cub (Rotax) RPM gauges, and it adds a new RPM Percent gauge for turbine and jet aircraft. 

The standard RPM instrument tests the engine type and the engine's max rated RPM to determine whether to display the prop RPM in the standard gauge, the engine RPM in the Savage Cub gauge, or the turbine N1 percent in the RPM Percent gauge.

These changes have been tested with all the aircraft in MSFS, plus a community generated aircraft: the indicated RPM is the same as the value displayed in the aircraft's native instrument panel. 

- Changed the computation of the indicator needle angle on the standard RPM and Savage Cub gauges
- Added an RPM Percent gauge
- Fixed display of elapsed time on Savage Cub gauge
- Added several SimConnect engine vars

Closes #26

### CODE REVIEW

**Review by scott-vincent — COMMENTED** [review]
Does this still work for all planes, e.g. airliners too? I think there may be problems as you've switched from using rpmPercent to rpmEngine. If so, probably need your new code just for Cessna and original code for all others. I may be wrong, not tried your changes.

**Comment by emxsys** [comment]
Thanks for the review. Your concern is valid. I will investigate the non-piston aircraft.

**Comment by emxsys** [comment]
@scott-vincent, I plan to add some more engine related vars to perform conditional tests.

- **Engine Type** enum to test if the aircraft has piston, turboprop or jet engine(s) so we can determine whether to display traditional tachometer or a Percent RPM gauge (bitmap to be developed)
- **Eng Max RPM** value to determine what type of tachometer to display (e.g., Cessna vs Cub)
- **Eng Manifold Pressure** value to be used in forthcoming Manifold Pressure gauge (used in complex aircraft with constant speed props)

With these vars and one more RPM bitmap I think we can have an RPM gauge that works for _all_ aircraft.

Below are the proposed changes to the data link.  Does it look right?
```
--- a/instrument-data-link/simvarDefs.cpp
+++ b/instrument-data-link/simvarDefs.cpp
@@ -94,6 +94,9 @@ const char* SimVarDefs[][2] = {
     { "General Eng Oil Temperature:1", "fahrenheit" },
     { "General Eng Oil Pressure:1", "psi" },
     { "General Eng Exhaust Gas Temperature:1", "celsius" },
+    { "Engine Type", "enum" },
+    { "Eng Max RPM", "rpm" },
+    { "Eng Manifold Pressure:1", "inch of mercury" },
     { "Eng Fuel Flow GPH:1", "gallon per hour" },
     { "Suction Pressure", "inch of mercury" },
     { "Atc Id", "string64" },
diff --git a/instrument-data-link/simvarDefs.h b/instrument-data-link/simvarDefs.h
index dbab97c..b81eef8 100644
--- a/instrument-data-link/simvarDefs.h
+++ b/instrument-data-link/simvarDefs.h
@@ -96,6 +96,9 @@ struct SimVars
     double oilTemp = 75;
     double oilPressure = 50;
     double exhaustGasTemp = 0;
+    double engineType = 0;
+    double engineMaxRpm = 0;
+    double engineManifoldPressure = 0;
     double engineFuelFlow = 0;
     double suctionPressure = 1;
     char atcTailNumber[64] = "\0";
```

**Comment by emxsys** [comment]
Here's an example of the Percent RPM vs traditional tachometer:

image

**Comment by scott-vincent** [comment]
New Data Link vars look good to me. New gauge looks great.

**Comment by emxsys** [comment]
@scott-vincent, this is a work in progress, however, the new RPM Percent gauge can be tested with the Airbus and the current Data-Link (v1.4.2).  

TODO:
- Darken background of RPM Percent gauge. (I snagged/edited an image off the internet; I haven't yet mastered enough GIMP skills to create a dial radial)
- Add engine type sim vars so as to detect turbine and jet engines

**Review by scott-vincent — COMMENTED** [review]
You don't want the changes you've made to instrument-panel.cpp because "RPM Percent" is just a variation of "RPM" and is chosen based on the current aircraft, not by the settings (also needs to be removed from settings file).  I see you have already added the code into rpm.cpp to instantiate a new rpmPercent instrument when the aircraft is A320neo. This is all that is needed. It's similar to the instruments in the genericFast folder. Maybe we should rename that folder to just generic and then move rpmPercent into there too (or you could call it rpmFast if you want).

I still also think you need to change the rpm.cpp code so that it only uses the rpmEngine var for the Cessna and uses the original code with rpmPercent var for everything else. This is so it still works for any aircraft that isn't using the 'fast' variant, i.e. everything apart from the A320neo currently.

Not that if you don't want to spend your time developing the rpmPercent gauge (if you never fly airliners) then that is fine by me. Just make your new changes specific to the Cessna and the gauge will continue to work as it did before for the other aircraft. It's entirely up to you, I don't mind either way.

**Comment by emxsys** [comment]
Thanks for the review. :- )  I'll make the requisite changes to instrument-panel.cpp and settings.

> I still also think you need to change the rpm.cpp code so that it only uses the rpmEngine var for the Cessna and uses the original code with rpmPercent var for everything else.

I'm currently testing the new `simVars->EngineType` and instantiating `rpmPercent` for turbine and jet engines.  Seems to work!  Also, I just discovered that I can use `Max Rated Engine RPM` to instantiate the "High RPM" gauge (`rpmSavageCub`) if the `engineType` is piston and max RPM > 3500, otherwise use the standard RPM gauge for piston engines.  So far, I've successfully tested with the Airbus, 747, Longitude, TBM, Caravan, Savage Cub, Bonanza, 172, and the community's GotGravel Carbon Cub STOL. 

_With the use of these new engine vars, it appears no longer necessary to make choices based on aircraft make/model._

One minor issue I've identified so far is the `rpmPercent` var is not in-sync with the RPM displayed in the Cessna Caravan's and TBM's G1000.  I've tried other "RPM percent" vars without success.  I don't know what value those aircraft are using for RPM .Good news is the 'rpmPercent` is working correctly for the Airbus, 747 and Cessna Longitude.  

I'll be checking these changes in later today for your review, plus a pull request for the data link.

**Comment by emxsys** [comment]
I've completed all the changes for this pull request save for renaming/moving files.  On that topic, there's possibly more to consider, such as possibly renaming/copying `rpmSavageCub` to something like `rpmHighRev` for the "generic" treatment.  You can assign that to me if you wish or handle it later after more thought.

I've also update the PR's description.

In summary, we have a robust RPM instrument that should work correctly for all existing and future aircraft.  I've tested it with all the MSFS Premium Deluxe aircraft plus a community developed plane.

- For jets and turbines, we display the "Turbine Engine N1" percent, the same value the native instrument panels are displaying. BTW: I think this value is the first stage compressor in a turbine engine. Also, this is not always the same as the `rpmPercent` previously used (there was a big difference in values with all the GA turbine aircraft).
- For the high-reving Rotax piston engines (max RPM > 5000), we display the "engine RPM" in the Savage Cub instrument. The accuracy has been improved. In testing, I discovered other aircraft besides the Cub and Ultra use this engine, and I was happy to see the correct RPM displayed in your instrument-panel.
- For all other piston engine aircraft we display the "prop RPM" on the standard gauge. FYI: Prop RPMs are typically kept less than 2700 to keep the prop tips from going supersonic.  On most engines with props directly affixed to the engine, the prop RPM and engine RPM are the same.  In testing, I discovered the Diamond DA40 and DA62 have higher-reving engines (a max RPM of 3880) with constant speed props.  In these scenarios, the prop RPM is less than the engine RPM and the prop RPM is what is displayed in the native instrument panels and in your instrument-panel.

Thanks for your help with the graphics!

**Review by scott-vincent — APPROVED** [review]
A great addition to the instrument panel. Thanks for your hard work.

**Pull request merged**
